<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <!-- https://learn.microsoft.com/nuget/consume-packages/Central-Package-Management?WT.mc_id=DT-MVP-5003472#transitive-pinning -->
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.300" />
    <PackageVersion Include="MSTest" Version="4.3.0" />
    <PackageVersion Include="NonBlocking" Version="2.1.2" />
    <PackageVersion Include="NSubstitute" Version="6.0.0" />
  </ItemGroup>
</Project>
